# Generated by Django 5.2 on 2025-05-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approval_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
