# Generated by Django 5.2 on 2025-05-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rating_score'),
        ('app', '0002_alter_refundrequest_approval_date_and_more'),
    ]

    operations = [
    ]
